
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.ActionEvent;
import java.sql.*;
import java.util.Calendar;

/**
 *
 * @author Owner
 */
public class DoctorGUI extends javax.swing.JFrame {
	public Connection myConn;
	int doctorLogin;

	/**
	 * Creates new form DoctorGUI
	 */
	public DoctorGUI(Connection _myConn, int doc) {
		initComponents();
		myConn = _myConn;
		doctorLogin = doc;
		jLabel1.setText("LoginID: " + doc);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		choice1 = new java.awt.Choice();

		choice1.add("Create");
		choice1.add("Update");
		choice1.add("Delete");

		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField(5);
		jLabel6 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField(5);
		jLabel7 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField(5);
		jLabel8 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField(5);
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField(5);
		jLabel11 = new javax.swing.JLabel();
		jTextField6 = new javax.swing.JTextField(5);
		jLabel12 = new javax.swing.JLabel();
		jTextField7 = new javax.swing.JTextField(5);
		jPanel1 = new javax.swing.JPanel();
		jLabel14 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField(5);
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("LoginID:");

		jLabel4.setText("Treatment");

		jLabel5.setText("Patient_ID");

		// jTextField1.setText("jTextField1");

		jLabel6.setText("Medicine");

		// jTextField2.setText("jTextField2");

		jLabel7.setText("Frequency");

		// jTextField3.setText("jTextField3");

		jLabel8.setText("Date");

		// jTextField4.setText("jTextField4");

		jLabel9.setText("Patient Lookup");

		jLabel10.setText("First Name");

		// jTextField5.setText("jTextField5");

		jLabel11.setText("Last Name");

		// jTextField6.setText("jTextField6");

		jLabel12.setText("Phone Number");

		// jTextField7.setText("jTextField7");

		// jLabel14.setText("jLabel14");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(
				jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
						jPanel1Layout.createSequentialGroup().addComponent(jLabel14).addGap(0, 362, Short.MAX_VALUE)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addComponent(jLabel14).addGap(0, 26, Short.MAX_VALUE)));

		jLabel13.setText("Show Patient Treatments:");

		// jTextField8.setText("jTextField8");

		jButton1.setText("Lookup Treatments");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Update Treatment");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("Lookup Patient Info");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(32, 32, 32)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(layout.createSequentialGroup()
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jLabel2))
										.addComponent(jLabel3)
										.addGroup(layout.createSequentialGroup().addComponent(jLabel10)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jLabel11)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(18, 18, 18).addComponent(jLabel12)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addGap(30, 30, 30).addComponent(jButton3))
										.addComponent(jLabel9))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jButton2)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel13).addGap(18, 18, 18)
										.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(39, 39, 39).addComponent(jButton1))
								.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel4)
								.addGroup(layout.createSequentialGroup()
										.addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(28, 28, 28).addComponent(jLabel5)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel6).addGap(18, 18, 18)
										.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel7)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(18, 18, 18).addComponent(jLabel8)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(0, 132, Short.MAX_VALUE)))));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(24, 24, 24)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(jLabel2))
				.addGap(22, 22, 22).addComponent(jLabel4)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(choice1, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jLabel5)
								.addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel6)
								.addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel7)
								.addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel8).addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jLabel3)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(jButton2)
				.addGap(30, 30, 30).addComponent(jLabel9)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel10)
						.addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel11)
						.addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jLabel12)
						.addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton3))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
				.addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addGap(50, 50, 50)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel13)
						.addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addComponent(jButton1))
				.addContainerGap(113, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	// Patient lookup
	protected void jButton3ActionPerformed(ActionEvent evt) {
		String firstname = jTextField5.getText();
		String lastname = jTextField6.getText();
		String phonenumber = jTextField7.getText();

		// Select * from patient where (FirstName = 'Bob' AND LastName = 'Ross') OR
		// (PhoneNumber = 'asdfas');
		String query = "Select * from patient where (FirstName = '" + firstname + "' AND LastName = '" + lastname
				+ "') OR (PhoneNumber = '";
		String extra = phonenumber + "');";
		query = query + extra;
		String pat = "";
		Statement statement;
		try {
			statement = myConn.createStatement();
			ResultSet set = statement.executeQuery(query);
			boolean first = true;
			while (set.next()) {
				if (first) {
					pat = set.getString("Patient_ID");
				}
				first = false;
			}

		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		jLabel14.setText("The patient ID is " + pat);
	}

	// Updte treatment
	protected void jButton2ActionPerformed(ActionEvent evt) {
		String crud = choice1.getSelectedItem();
		if (crud == "Create") {

			// Get doctorID from loginID
			// select from login where LoginID = doctorLogin;
			String getDoc = "Select * from Login where Login_ID = " + doctorLogin;
			int docID = 0;

			int i = 0;
			// i = jButton2.getSelectedIndex();

			try {
				Statement statement = myConn.createStatement();
				ResultSet set = statement.executeQuery(getDoc);
				while (set.next()) {
					docID = set.getInt("Doctor_ID");
				}
			} catch (SQLException e) {
				e.printStackTrace();
			}

			// Create Treatment for given patient and known doctor id
			String PatID = jTextField1.getText();
			String medicine = jTextField2.getText();
			String freq = jTextField3.getText();
			java.sql.Date ourJavaDateObject = new java.sql.Date(Calendar.getInstance().getTime().getTime());
			String date = "'" + ourJavaDateObject.toString() + "'";
			String q = "insert into treatment(Patient_ID, Doctor_ID, Medicine, Frequency, DateOfTreatment) values ("
					+ PatID + "," + docID + ",'" + medicine + "', '" + freq + "', " + date + ");";

			try {
				Statement statement = myConn.createStatement();
				statement.executeUpdate(q);
			} catch (SQLException e) {
				e.printStackTrace();
			}
		}

		// DELETE
		// DELETE FROM treatment where Patient_ID = PATID AND MEDICINE = medicine and
		// Frequency = frequency
		if (crud == "Delete") {
			String PatID = jTextField1.getText();
			String medicine = jTextField2.getText();
			String freq = jTextField3.getText();
			String q = "Delete from treatment where Patient_ID = " + PatID + " AND MEDICINE = '" + medicine + "'"
					+ " AND FREQUENCY = '" + freq + "'";
			System.out.println(q);

			try {
				Statement statement = myConn.createStatement();
				statement.executeUpdate(q);

			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}
		if (crud == "Update") {
			String PatID = jTextField1.getText();
			String medicine = jTextField2.getText();
			String freq = jTextField3.getText();
			String q = "update treatment set Frequency = '" + freq + "' where Patient_ID = " + PatID + " AND MEDICINE = '" + medicine + "'";
			System.out.println(q);

			try {
				Statement statement = myConn.createStatement();
				statement.executeUpdate(q);

			} catch (SQLException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}

		}

	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String patID = jTextField8.getText();
		int pat = Integer.parseInt(patID);
		PatientTreatments patTreat = new PatientTreatments(myConn, pat);
		patTreat.setVisible(true);
	}

	// Variables declaration - do not modify
	private java.awt.Choice choice1;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	private javax.swing.JTextField jTextField6;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	// End of variables declaration
}
